Revert to openssl (rather than ssl-cert), generate cert in postinst, install template via rules, cleanup cert in postrm

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -2,11 +2,24 @@
 
 set -e
 
+SSL_CERT=/etc/naviserver/naviserver.pem
+TEMPLATE=/etc/naviserver/naviserver.cnf
+
 if [ "$1" = "configure" ]; then
 
 	# Create default certificate
-    	if [ ! -f /etc/naviserver/default.pem ]; then
-        	make-ssl-cert /usr/share/ssl-cert/ssleay.cnf /etc/naviserver/default.pem
+    	if [ ! -f $SSL_CERT ]; then
+		TMPOUT=`mktemp` || exit 1
+		TMPFILE=`mktemp` || exit 1
+		if [ ! HostName="$(hostname -f)" ]; then
+			HostName="$(hostname)"
+		fi
+		sed -e s#@HostName@#"$HostName"# $TEMPLATE > $TMPFILE
+		if [ ! openssl req -config $TMPFILE -new -x509 -days 3650 -nodes -out $SSL_CERT -keyout $SSL_CERT > $TMPOUT 2>&1 ]; then
+			echo "Could not create certificate. Openssl output was:" >&2
+			cat $TMPOUT >&2
+			exit 1
+    		fi
     	fi
 fi
 
